---
development:
  cloud_name: diekjezbk
  api_key: '398144785841944'
  api_secret: uxIsY1MRVVdx7yuK4sxDEj6nANY
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: diekjezbk
  api_key: '398144785841944'
  api_secret: uxIsY1MRVVdx7yuK4sxDEj6nANY
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: diekjezbk
  api_key: '398144785841944'
  api_secret: uxIsY1MRVVdx7yuK4sxDEj6nANY
  enhance_image_tag: true
  static_file_support: false
